insert into pet values (1, 12,'M','image1.jpg','Negão', 1, 'Cane corso');
insert into pet values (2, 11,'F','image2.jpg','Neguinha', 2, 'Cane corso');
insert into pet values (3, 9,'F','image2.jpg','Nina', 2, 'Cane corso');
insert into pet values (4, 9,'F','image2.jpg','Nila', 2, 'Cane corso');
insert into pet values (5, 9,'M','image1.jpg','Nino', 2, 'Cane corso');
insert into pet values (6, 6,'M','image1.jpg','Boo', 3, 'Cane corso');
insert into pet values (7, 6,'M','image1.jpg','Scooby', 3, 'Cane corso');
insert into pet values (8, 6,'M','image1.jpg','Clifford', 3, 'Cane corso');
insert into pet values (9, 6,'F','image2.jpg','Laika', 4, 'Cane corso');
insert into pet values (10, 2,'M','image1.jpg','Nhoque ', 9, 'Cane corso');
insert into pet values (11, 2,'M','image1.jpg','Quindim', 9, 'Cane corso');
insert into pet values (12, 2,'F','image2.jpg','Panqueca', 9, 'Cane corso');
insert into pet values (13, 2,'F','image2.jpg','Paçoca', 9, 'Cane corso');
insert into pet values (14, 2,'F','image2.jpg','Bisteca', 9, 'Cane corso');
insert into pet values (15, 2,'M','image1.jpg','Torresmo ', 9, 'Cane corso');